# Generated by Django 6.0.2 on 2026-03-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_general', 'Admin General'), ('admin', 'Administrador'), ('jefe_taller', 'Jefe de Taller'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
