# Generated by Django 6.0.2 on 2026-03-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
