# Generated by Django 6.0.2 on 2026-03-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0002_remove_ordentrabajo_esquematrabajo_trabajador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('descripcion_trabajo', models.TextField(blank=True)),
                ('porcentaje_trabajo', models.IntegerField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')])),
                ('entregado', models.BooleanField(default=False)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='ordenes.ordentrabajo')),
                ('trabajadores', models.ManyToManyField(related_name='asignaciones', to='ordenes.trabajador')),
            ],
        ),
    ]
