# Generated by Django 6.0.2 on 2026-03-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionot',
            name='descripcion_trabajo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='asignacionot',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionot',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
