# Generated by Django 6.0.2 on 2026-03-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('ordenes', '0003_alter_ordentrabajo_trabajadores'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignacion',
            new_name='AsignacionOT',
        ),
        migrations.AlterField(
            model_name='asignacionot',
            name='trabajadores',
            field=models.ManyToManyField(related_name='asignaciones', to='trabajadores.trabajador'),
        ),
    ]
