# Generated by Django 6.0.2 on 2026-02-19 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombreCliente', models.CharField(max_length=250)),
                ('rutCliente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('mailCliente', models.CharField(max_length=250)),
                ('telefonoCliente', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOT',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='NivelUrgencia',
            fields=[
                ('idNU', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcionNU', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('rutResponsable', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreResponsable', models.CharField(max_length=250)),
                ('mailResponsable', models.EmailField(max_length=250)),
                ('telefonoResponsable', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('rutSolicitante', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreSolicitante', models.CharField(max_length=250)),
                ('mailSolicitante', models.EmailField(max_length=250)),
                ('telefonoSolicitante', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('idOT', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraSolicitud', models.DateTimeField()),
                ('fechaEntregaTrabajo', models.DateField()),
                ('numeroCotizacion', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=255)),
                ('descripcionTrabajo', models.CharField(max_length=500)),
                ('esquemaTrabajo', models.CharField(max_length=1000)),
                ('porcentajeAvance', models.FloatField()),
                ('fechaAsignacion', models.DateField()),
                ('fechaEntregaPT', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.cliente')),
                ('estadoOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.estadoot')),
                ('nivelUrgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.nivelurgencia')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.responsable')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('idCC', models.AutoField(primary_key=True, serialize=False)),
                ('aprobado', models.CharField(max_length=2)),
                ('observaciones', models.CharField(max_length=500)),
                ('fechaRevision', models.DateField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordentrabajo')),
            ],
        ),
    ]
