# Generated by Django 6.0.2 on 2026-03-23 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('numero', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Este campo debe contener exactamente 8 dígitos.', regex='^\\d{8}$')])),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero_cotizacion', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Este campo debe contener exactamente 8 dígitos.', regex='^\\d{8}$')])),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('atencion', models.CharField(blank=True, max_length=255)),
                ('responsable', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('nivel_urgencia', models.CharField(blank=True, max_length=100)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'ordentrabajo',
                'ordering': ['-numero'],
            },
        ),
    ]
