# Generated by Django 6.0.2 on 2026-03-25 20:41

import django.db.models.deletion
import ordenes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='comentario_detalle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AdjuntoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=ordenes.models.ruta_adjunto_ot)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='ordenes.ordentrabajo')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_ot_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto OT',
                'verbose_name_plural': 'Adjuntos OT',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
