# Generated by Django 6.0.2 on 2026-03-05 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='esquemaTrabajo',
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rutTrabajador', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreTrabajador', models.CharField(max_length=250)),
                ('telefonoTrabajador', models.CharField(blank=True, max_length=12, null=True)),
                ('mailTrabajador', models.EmailField(blank=True, max_length=250, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, to='ordenes.trabajador'),
        ),
    ]
