# Generated by Django 6.0.2 on 2026-03-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_remove_ordentrabajo_esquematrabajo_trabajador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, related_name='ordenes', to='ordenes.trabajador'),
        ),
    ]
